name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [56, 70, 71, 72, 73, 74]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: export TAG_VERSION=${PHP_VERSION:0:1}.${PHP_VERSION:1:1} && docker build . --file Dockerfile-${{ matrix.php_version }} --tag laradock/php-fpm:$(date +%s)-${TAG_VERSION}
      env:
        PHP_VERSION: ${{ matrix.php_version }}
      
    - name: show image list
      run: docker image ls
