name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [56, 70, 71, 72, 73, 74]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-${{php_version}} --tag laradock/php-fpm:$(date +%s)-${{php_version}}
