name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpversion: [56, 70, 71, 72, 73, 74]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile-${{phpversion}} --tag laradock/php-fpm:$(date +%s)-${{php_version}}
